'use strict';

export const routes = [
    {
        name: 'home',
        path: '/'
    }, {
        name: '/design/colors',
        path: '/design/colors'
    }, {
        name: '/design/typography',
        path: '/design/typography'
    }, {
        name: '/design/iconography',
        path: '/design/iconography'
    }, {
        name: '/design/motion',
        path: '/design/motion'
    }, {
        name: '/ui/buttons',
        path: '/ui/buttons'
    }, {
        name: '/ui/buttons-group',
        path: '/ui/buttons-group'
    }, {
        name: '/ui/labels-badges',
        path: '/ui/labels-badges'
    }, {
        name: '/ui/tables',
        path: '/ui/tables'
    }, {
        name: '/ui/alerts',
        path: '/ui/alerts'
    }, {
        name: '/ui/dropdown',
        path: '/ui/dropdown'
    }, {
        name: '/ui/autocomplete',
        path: '/ui/autocomplete'
    }, {
        name: '/ui/tags',
        path: '/ui/tags'
    }, {
        name: '/ui/multiple',
        path: '/ui/multiple'
    }, {
        name: '/ui/panels',
        path: '/ui/panels'
    }, {
        name: '/ui/spinner',
        path: '/ui/spinner'
    }, {
        name: '/ui/cards',
        path: '/ui/cards'
    }, {
        name: '/ui/features',
        path: '/ui/features'
    }, {
        name: '/ui/breadcrumb',
        path: '/ui/breadcrumb'
    }, {
        name: '/ui/lists',
        path: '/ui/lists'
    }, {
        name: '/ui/form-elements',
        path: '/ui/form-elements'
    }, {
        name: '/ui/select',
        path: '/ui/select'
    }, {
        name: '/ui/datepicker',
        path: '/ui/datepicker'
    }, {
        name: '/ui/pagination',
        path: '/ui/pagination'
    }, {
        name: '/ui/progress-bars',
        path: '/ui/progress-bars'
    }, {
        name: '/ui/modals',
        path: '/ui/modals'
    }, {
        name: '/ui/tabs-pills',
        path: '/ui/tabs-pills'
    }, {
        name: '/ui/accordion',
        path: '/ui/accordion'
    }, {
        name: '/ui/tooltips',
        path: '/ui/tooltips'
    }, {
        name: '/ui/text-inputs',
        path: '/ui/text-inputs'
    }, {
        name: '/ui/toaster',
        path: '/ui/toaster'
    }, {
        name: '/product-brand/our-logo',
        path: '/product-brand/our-logo'
    }, {
        name: '/product-brand/brand-book',
        path: '/product-brand/brand-book'
    }, {
        name: '/documentation/compatibility',
        path: '/documentation/compatibility'
    }, {
        name: '/documentation/using-with',
        path: '/documentation/using-with'
    }, {
        name: '/documentation/getting-started',
        path: '/documentation/getting-started'
    }
];